### ISSUE TITLE
Inclusivity WG Meeting - 2016-03-03 10:30 PST

### ISSUE THREAD

**Issue by nebrius** [nodejs/inclusivity#103]
# WG Meeting Agenda Template

Participant Link: https://plus.google.com/events/c8cvr7e7f2bfca533oebaovbut4
Observer Link: http://www.youtube.com/watch?v=j_zlOIdDqyE

## Roles
- Agenda: @nebrius
- Meeting Notes: @beaugunderson
- Facilitator:

## Agenda

- <h3>Pre-meeting</h3>
   - Deliberate TSC nomination
   - Discuss WG applications
   - _Note: this section will not be recorded for privacy reasons_
- <h3>Introductions</h3>
- <h3>Working Group Operations</h3>
   - Continuous translation threads for important discussions #102 (needs an owner?)
   - Create a history document #85 (@nebrius)
   - Inclusivity WG as default moderation team #79 (@nebrius, @emilyrose)
   - TSC request for a nomination to the TSC #78 (everyone)
   - ~~Draft Proposal: Rotating Meeting Time #74 (@Trott)~~
   - Identify the roles and responsibility of being a member of this WG #65 (@juliepagano)
- <h3>Activities</h3>
- <h3>Open PRs</h3>
   - Created the history document https://github.com/nodejs/inclusivity/pull/99
   - Initial draft of roles and responsibilities https://github.com/nodejs/inclusivity/pull/101
- <h3>Deliverables</h3>
  - Schedule Next Meeting
  - What do we want to accomplish in the next week?

**Comment by Trott** [comment]
More likely than not, I can't make this meeting, but I did want to note for this item:

> Draft Proposal: Rotating Meeting Time

I don't really have much to say about it. That was me putting together a straw proposal. What the next steps are, if any, I'm not sure. I'm hoping someone has an opinion on that and cares enough to push that opinion forward. I fully expect that anything we do along these lines will end up looking significantly different from my initial proposal. At least, that's been my expectation from the outset.

**Comment by sup** [comment]
won't make it - sorry!

**Comment by nebrius** [comment]
FYI we decided to postpone till next week. Several people had last minute scheduling conflicts.

**Comment by Charlotteis** [comment]
Suggestion for this WG Meeting Agenda Template: including times of different time zones.
10:30PST is:
13:30 (Thursday) ET
18:30 (Thursday) GMT London
19:30 (Thursday) Frankfurt, Germany
00:00 (Friday) IST Chennai
02:30 (Friday) HKT Hong Kong

**Comment by Fishrock123** [comment]
@Charlotteis for the CTC / TSC meetings we use some tools to show the local time: https://github.com/nodejs/node/issues/5274

**Comment by Charlotteis** [comment]
@Fishrock123 I like that :)
Just realised I missed the meeting despite it being in my calendar, too :(

**Comment by hg** [comment]
@Charlotteis i don't think it happened because almost nobody was ready :P

**Comment by nebrius** [comment]
gah, sorry, forgot to mention here that we postponed (again). Sorry everyone for the lack of meetings, a good chunk of the WG members are swamped with other things right now. From the sounds of it, things should clear up for several of us soon though, so I think we can probably do another meeting in two weeks or so.

**Comment by nebrius** [comment]
A note to anyone who will be joining us via the observer link: since we have a few things that need to be discussed in private first, the broadcast will start later than usual. Sorry for the inconvenience everyone.

**Comment by nebrius** [comment]
Closing since the meeting is done :)
