### ISSUE TITLE
Use the Foundation's YouTube channel

### ISSUE THREAD

**Issue by williamkapke** [nodejs/inclusivity#107]
First I want to say that I really enjoy this groups videos. I mean... the spirit, tone and effort put in to it is terrific. I especially appreciate that you call out `action items`/`deliverables` and use the "raise the hand" approach to coordinate. Some meeting videos I've seen have a strange sense of tension that I think adds to the [intimidation and "scary"](https://github.com/nodejs/inclusivity/issues/86) factor. Kudos everyone!

On to the "issue" portion... your videos could be more discoverable. I'm [trying to encourage](https://github.com/nodejs/TSC/issues/68) putting them on the official [Node.js Foundation YouTube channel](https://www.youtube.com/nodejs+foundation). Then observers (like me!) always just need to tune in to https://www.youtube.com/nodejs+foundation/live to see what's happening LIVE!

@nebrius [already chimed in on that thread](https://github.com/nodejs/TSC/issues/68#issuecomment-197622847)- but I wanted to leave a trail of that info here too. Maybe this is already good-to-go!

It would be cool if the previous videos could be moved- but I guess that isn't super easy. Let me know if I can help!

**Comment by nebrius** [comment]
If you can find an easier way to transfer videos, that would be awesome! Last I heard, you technically have to do a remix and re-upload that, there's no way to actually transfer videos :( I haven't tried myself though.

I definitely plan on making sure all future videos are on the node.js channel though (I've gotten the necessary permission bits set up).

**Comment by nebrius** [comment]
Also, I almost forgot, [we have a template](https://github.com/nodejs/inclusivity/blob/master/docs/POLICY_ISSUES.md) for filing issues that was developed someone recently. Can you update your issue to follow the template?

I realize that this isn't very discoverable, so I filed #110 to fix that :)

**Comment by williamkapke** [comment]
@nebrius Iiiiiiinteresting. Ok, so I stared converting it- but then couldn't fit the square peg in the round hole so-to-speak. According to the template, I'm out of lines of allowable Purposes:
- Question  <sub>.... nooo</sub>
- Request for changes to a policy <sub>.... nooo</sub>
- Request for new policy <sub>... maaaybe a Meeting Procedures Policy......?</sub>

It would appear that the issue template doesn't offer an avenue for outside feedback on non-Policy related process. Reading it makes me think I should first open an issue to request a change to the POLICY_ISSUE.md but I think that would come off as passive-aggressive which I don't want.

...and now I'm really off "Focus" I'm sure. I feel I've accomplished my goal of linking the issue here to create a backstory for others. So feel free to just close this.

> If you can find an easier way to transfer videos, that would be awesome!

I have the videos downloaded- but, unfortunately, I'm far from someone with access to be able to upload them. I am more than willing to commit time to help though.

**Comment by nebrius** [comment]
Thanks for looking in to this!

> It would appear that the issue template doesn't offer an avenue for outside feedback on non-Policy related process. Reading it makes me think I should first open an issue to request a change to the POLICY_ISSUE.md but I think that would come off as passive-aggressive which I don't want.

Totally not passive aggressive at all! We basically created templates for known issues we had previously received. Perhaps we need some sort of "administrative task" template.

So, the point of "focus" is to define what is on topic and what is derailing. Given the topics we often discuss, derailments are sadly common, and this section is intended to help. I doubt moving videos around on YouTube will be controversial ;-)

In the meantime we can leave this issue as is.

**Comment by mikeal** [comment]
FTR, the youtube channel is connected to our Google Plus account. G+ only allows one "owner" who can add additional people as "managers." I'm the owner, and I can add anyone who is doing meetings as a manager which will allow you to post to the youtube channel. I wish we could have a few owners to make this easier but unfortunately this is a G+ constraint.

**Comment by nebrius** [comment]
Our most recent meeting was broadcast from the Node.js YouTube channel 🎉
