### ISSUE TITLE
Make use of issue templates

### ISSUE THREAD

**Issue by nebrius** [nodejs/inclusivity#110]
## Purpose

Issue templates were recently added to GitHub. We should make use of them to help people file more actionable issues.

## Proposal

As it turns out, we've had an issue template for a while at https://github.com/nodejs/inclusivity/blob/master/docs/POLICY_ISSUES.md. It will probably need to be adapted a bit to be more "template like."

While we're at it, we should also link to our POLICY_ISSUES document from the CONTRIBUTING file, as that seems to be missing currently.

## Focus

This issue is focused on getting the existing information in the POLICY_ISSUES file into a template

Examples of off-topic discussions include:
- Changing the content in POLICY_ISSUES
- The necessity of having a policy issue

As always, if you would like to discuss these off-topic issues, please open a new issue that follows our [issue policy](https://github.com/nodejs/inclusivity/blob/master/docs/POLICY_ISSUES.md).

**Comment by scottgonzalez** [comment]
Adapting `POLICY_ISSUES.md` into an issue template will be fairly tough because that's a *very* lengthy document compared to a template. We'd probably want to just provide the desired structure with a note to read the policy document.

Perhaps something like:

```md
<!--
Thanks for your interest in improving inclusivity and diversity within the Node.js project. Please read the following policy document to ensure the issue stays on topic and can be resolved quickly:
https://github.com/nodejs/inclusivity/blob/master/docs/POLICY_ISSUES.md
-->

## Purpose

<!-- Please provide a brief description of what you would like to see addressed. -->

## Proposal

<!-- For policy issues only, if you have an idea of what the policy should look like, include a summary of it here. -->

## Focus

<!-- Please define what is "on topic" and what is "off topic." -->

Some off topic examples include, but are not limited to:
- ...
```

The use of HTML comments ensures that if someone files an issue and doesn't delete parts of the template, the instructions don't show up in the rendered issue.

**Comment by nebrius** [comment]
Love it! can you make a PR for that @scottgonzalez?
