### ISSUE TITLE
Create page for community members to join our Slack team

### ISSUE THREAD

**Issue by scottgonzalez** [nodejs/inclusivity#111]
To enable access to our public Slack channels, we should host a page that allows people to join our Slack team without a manual approval/invitation process.

* We'll tie Slack invites to GitHub users so we can track who has been invited and efficiently manage banning across both mediums if necessary.
* If the GitHub account doesn't have a public email address, we'll ask the user to provide their email address for the Slack invite.
* A record of the GitHub username and email address will be logged for future reference.
  * Should this list be private to the team? As far as I can tell, Slack doesn't allow hiding email addresses anyway.
* Users are auto-invited to Slack via the Slack API.
* GitHub accounts must be at least 30 days old in order to get a Slack invite.
  * This avoid trolls creating throwaway accounts to continue trolling in Slack.
* The WG members can manually approve a new GitHub account.

**Comment by strand** [comment]
I really like this idea. Because, as a newcomer, when I want to help, I don't even—can't even—know who to ask where my effort should be applied.

**Comment by scottgonzalez** [comment]
I have the basics of this implemented. Should I create a new repo and file a PR against it? If so, what should we call the repo? I've got follow up questions too, like who's responsible for deployment, infrastructure, etc.

**Comment by hg** [comment]
@scottgonzalez i'd say, yeah, go ahead and create the repo

**Comment by scottgonzalez** [comment]
https://github.com/nodejs/inclusivity-slack-inviter/pull/1

**Comment by Charlotteis** [comment]
Has the community page been hosted anywhere?

**Comment by 59** [comment]
@Charlotteis not yet, we're still figuring out if the foundation has any resources to host this

**Comment by nebrius** [comment]
It hasn't yet, I'm trying to work on it while I travel, so stay tuned!

**Comment by Charlotteis** [comment]
Heroku might be a good place to host such a thing? But I'm sure there must be some foundation way of doing this. I know that @nebrius has tied it to their own domain for now :)
