### ISSUE TITLE
Not listed on the Working Groups page

### ISSUE THREAD

**Issue by williamkapke** [nodejs/inclusivity#112]
## Purpose
Question:
This has been an official WG for awhile now! Why are you not on the [Working Groups Page](https://nodejs.org/en/about/working-groups)?

## Proposal
Submit a PR to https://github.com/nodejs/nodejs.org/edit/master/locale/en/about/working-groups.md to add this WG. It needs a small writeup about the group so I think someone from this group might want to provide that.

## Focus
This discussion is specifically to call out a TODO for the WG if applicable.

Some off topic examples include, but are not limited to:
- What the text be in the PR.

**Comment by nebrius** [comment]
We're not on that page because we're on [this on](https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md). That page is for Working Groups chartered by the CTC, but as was mentioned in https://github.com/nodejs/TSC/issues/76, we're chartered by the TSC.

**Comment by williamkapke** [comment]
Yeah, we're discovering that here:
https://github.com/nodejs/nodejs.org/pull/622

That page comes from the days before a Top-Level WG. I would like to get it updated to include both.

**Comment by nebrius** [comment]
I would be up for adding a note to the bottom of the CTC WG page saying "other working groups are chartered by the TSC, check them out here" or something, but we shouldn't be on the CTC's WG page because we are not chartered by the CTC.

**Comment by williamkapke** [comment]
That page is "Working Groups"... which has been traditionally the Core Working Groups, however that page is located on the main website at https://nodejs.org/en/about/working-groups. Think of it from a visitor's perspective, depending on how new they are (or maybe just a reporter/blogger)- they have no idea what a TSC or a CTC is... and I'm not sure it is too relevant at that point.

I'm putting together a PR that will have a Top-Level Working Group section and a Core Working Group section and nothing to do with Chartering.

If ya'll don't want to be listed, ok, I won't add a Top-Level Working section since you're the only one for now ;)

**Comment by nebrius** [comment]
I'm fine with adding us to the website, indeed I think we should be, but we should not be added to the repo the nodejs/node repo. I agree that it's important to surface this information to visitors, but it's important that we do so in a way that is accurate, otherwise we create more confusion for said visitors. ideally we would be listed accurately, but I would also rather us be unlisted than listed in a way that conveys false information.

**Comment by nebrius** [comment]
Oh wait, I misread nodejs/node.org as nodejs/node, sorry that was my mistake (we've had the discussion of ctc vs tsc so many times that my lizard brain pattern matched to those convos)

**Comment by williamkapke** [comment]
Please review https://github.com/nodejs/nodejs.org/pull/623

**Comment by williamkapke** [comment]
:boom: https://github.com/nodejs/nodejs.org/pull/623 landed!
