### ISSUE TITLE
Slack inviter doesn't work

### ISSUE THREAD

**Issue by williamkapke** [nodejs/inclusivity#123]
I tried it out and it appears to have some bugs.

## I am not @59 ...
![screenshot 2016-04-18 09 37 37](https://cloud.githubusercontent.com/assets/739813/14611907/64080a62-0549-11e6-97b0-2f08db13732e.png)

## It didn't work, I'm guessing it has a blank email address...??
![screenshot 2016-04-18 09 37 01](https://cloud.githubusercontent.com/assets/739813/14611909/65e5e516-0549-11e6-908f-5e0ad66c0119.png)

**Comment by scottgonzalez** [comment]
Hmm...I'm seeing this too. Very odd since the user info is tied to cookies.

**Comment by 59** [comment]
i can finally reveal that i have cookies that transcend time and space

(no but seriously this is weird)

**Comment by scottgonzalez** [comment]
Seems like `request.sessionID` is no longer a thing that exists in newer versions of Express...

**Comment by scottgonzalez** [comment]
This is unfortunate because it means that there need to be changes down in https://github.com/scottgonzalez/connect-oauth-github. I don't have time to work on this right now though. I can probably work on it tonight.

**Comment by nebrius** [comment]
Funny story, I had to deal with session stuff in express recently myself, and yeah it was spun off into https://github.com/expressjs/session.

**Comment by scottgonzalez** [comment]
> Funny story, I had to deal with session stuff in express recently myself, and yeah it was spun off into https://github.com/expressjs/session.

I'm not sure why both `express-session` and `cookie-session` exist in the express org, but switching to `express-session` fixed the problem without having to make any changes to `connect-oath-github` :-)

**Comment by scottgonzalez** [comment]
This should be fixed from https://github.com/nodejs/inclusivity-slack-inviter/issues/2. Can you verify?

**Comment by williamkapke** [comment]
Still some oddness... It is showing your name & email still. I cleared my cookies and did a refresh, but it didn't change. I clicked the button anyhow and it says I'm already a member :/

![image](https://cloud.githubusercontent.com/assets/739813/14725358/5d34591e-07d0-11e6-9d9f-6927bfe90b07.png)

Is this just me? Maybe... ::shrugs::

**Comment by scottgonzalez** [comment]
Ok. After my fix was merged, I tried to use the inviter and it showed my info, so I assumed it had been deployed again. I guess it was just restarted and not deployed. When I'm at a computer, I'll connect to the server and get it updated.

**Comment by scottgonzalez** [comment]
I just logged into the server and it was in fact still on the old code. I've updated it and restarted the process. I also went through the invitation process to ensure that when you test again you'll see the bug if it still exists.

**Comment by williamkapke** [comment]
🎉 Works now :D
