### ISSUE TITLE
Clean up Inclusivity GitHub team

### ISSUE THREAD

**Issue by nebrius** [nodejs/inclusivity#126]
## Purpose

I noticed that there are several people who are members of the inclusivity GitHub team that aren't members (check out https://github.com/orgs/nodejs/teams/inclusivity if you have the right permissions). The extra people on the list were added when the group was just forming, and we were unsure what roles/permissions people should have. Now that we have a defined roles and responsibilities policy, we should limit this to current members of the working group.

This is mostly an administrative task, but I wanted to open an issue so that people could be informed about this action.

_If you find you have been removed as a team member, this is why_. If you would like to remain on the team, please [apply to become a member](https://github.com/nodejs/inclusivity/blob/master/docs/POLICY_ADMISSIONS.md), we'd love to chat!

## Focus

This issue is about an administrative action to be taken, so lets keep focused on the administrative side of things here.

Some off topic examples include, but are not limited to:
- Why certain people are or are not members currently
- The membership process

**Comment by nebrius** [comment]
I just removed individuals from the team who are not members. I'm thinking about leaving this open for a few days to give people a chance to see it, then I'll close it.

**Comment by TheAlphaNerd** [comment]
fare well :P
