### ISSUE TITLE
Inclusivity WG Meeting - 2015-11-17 08:00 PST

### ISSUE THREAD

**Issue by nebrius** [nodejs/inclusivity#13]
There are a lot of open questions right now (basically all the other issues and PRs on this repo), and it was suggested in https://github.com/nodejs/diversity/pull/7 that we hold a meeting to try and iron out the really pressing issues.

I think this is a great idea, and I have a few questions I'd like to get feedback on:

- Who wants to participate?
- What times work for everyone?
- How long do we think the meeting should be?
- Should we use Google Hangouts on Air, and if so, how do we want to handle inviting people to participate? Open to all, first come first serve? Only to people in the Slack? Something in between?
- Other things not listed here?

List of people who have expressed interest in joining the meeting:

- @ashleygwilliams 
- @sup
- @Fishrock123 
- @juliepagano
- @thefourtheye
- @JungMinu
- @zkat

List of people who have expressed interest in joining, but in a less active/non-active role:

- @TheAlphaNerd
- @mikeal 
- @jedireza
- @nathan7 
- @nebrius

Proposed Agenda:

- Scope/mission of the WG
- The submission process for joining the WG
- Balancing privacy and transparency in public/private communication systems
- Moderation policies and enforcement
- Schedule and Assignment of Deliverables (when due, reviewed, submitted, and by who, to whom)

Deliverables:
- Membership Policy 1.0 (how to join, responsibilities)
- Charter 1.0
- CoC 1.0

Proposed time: Tuesday, November 17th at 16:00 UTC (08:00 PST, 11:00 EST, 17:00 CET, 21:30 IST)

**Comment by ashleygwilliams** [comment]
- hi i want to participate
- EST, work hours are fine for me
- cap it at an hour
- let's record it and cap it at 5-6 people
- an agenda and someone to keep us on task and someone to follow up

these opinions based on my experience with efficient meetings

**Comment by sup** [comment]
i'd be happy to participate (even though i have to work out some issues with my mic). as for times, i'd be free the entire weekend, but during weeks, 4-11pm CEST should be fine. for all the other points, i agree with @ashleygwilliams :)

**Comment by TheAlphaNerd** [comment]
If there is a seat let me know and I'll participate. That being said I would rather someone from an under represented group take part than myself.

**Comment by Fishrock123** [comment]
I am willing to participate for purposes of TSC representation if necessary. If so, I'll work around everyone else's times.

**Comment by mikeal** [comment]
I'd like to be in the meeting in a non-voting capacity and I shouldn't be considered a candidate for membership in the group, but I can fill in a lot of the context around governance and foundation resources and how all of that stuff works. I'm in Pacific time.

**Comment by nathan7** [comment]
I'd like to participate, I'm in CET (but I'll happily deal with whatever time).

**Comment by jedireza** [comment]
I'd like to be in the meeting. I'm in Pacific time. Like Myles, I'd like more people from under represented groups to attend.

**Comment by sup** [comment]
can you guys define 'underrepresented groups'? i'm a non-native english speaker and not from SF, so do i fit in any of those?

**Comment by ashleygwilliams** [comment]
gender, sexual orientation, race/ethnicity, economic status, age

**Comment by Fishrock123** [comment]
@mikeal can probably fill in for what I could so there's not much reason for me to be there then. (besides I have enough meetings already.)

**Comment by ashleygwilliams** [comment]
so:
- women
- people of color
- trans, gender queer 
- bisexual, homosexual, asexual
- poor
- people not in their 20s/30s

**Comment by TheAlphaNerd** [comment]
don't forget physical disabilities and non native english speakers

both a11y and i18n need to be deeply considered

**Comment by ashleygwilliams** [comment]
YES. thanks @TheAlphaNerd

**Comment by ashleygwilliams** [comment]
documenting this should maybe be one of the deliverables

**Comment by TheAlphaNerd** [comment]
anyone who feels they have an opinion that is not being represented should feel welcome to take part

**Comment by sup** [comment]
i see. i suppose i fit in quite well in some of those sections then, being german, asexual and younger than 20. neat

**Comment by nebrius** [comment]
FWIW I would like to be in, but in a non-voting capacity too, similar to @mikeal. I'm willing to play the role of moderator and/or note-taker.

**Comment by sup** [comment]
@nebrius could you keep something like a draft list of participants in your OP? i feel it'd clear things up a bit

**Comment by juliepagano** [comment]
I'm happy to participate:

- I'm on pacific time. Maybe suggest a few potential days/times and see which work best for everyone?
- Hour max time.
- +1 on having an agenda, facilitator, and people to follow up.

**Comment by sup** [comment]
regarding agendas, there are some tools to manage meeting agendas out there, aren't there? does anyone know of any?

**Comment by juliepagano** [comment]
A lofi list would probably suffice for the agenda. I don't think we need anything particularly complicated.

**Comment by Fishrock123** [comment]
Usually we just use google docs for agendas and notes, although you're welcome to use something else if preferred.

**Comment by sup** [comment]
ah no, i wouldn't want to burden anyone with creating a new account on a new service when we could just use google docs :P

**Comment by nebrius** [comment]
@sup good idea on the list of potential attendees. I updated the main issue

**Comment by nebrius** [comment]
I feel like, given the issues and discussions, that these are the key things we should discuss:

- Scope/mission of the WG
- The submission process for joining the WG
- Balancing privacy and transparency in public/private communication systems

What does everyone else think?

**Comment by juliepagano** [comment]
That sounds like a good list of things to focus on for the meeting.

**Comment by nebrius** [comment]
Just to confirm, everyone's timezones so far are CET (UTC+2), (EST (UTC-5), PST (UTC-8).

My understanding is CEST is not being used right now, so it's CET, right?

Did I miss any?

**Comment by mikeal** [comment]
Can we reach out to non-native english speakers and some people in international timezones?

**Comment by nebrius** [comment]
> Can we reach out to non-native english speakers and some people in international timezones?

Good call. @yosuke-furukawa, would you like to join this meeting?

**Comment by nathan7** [comment]
@nebrius Yup, CEST is not currently in use.

**Comment by Fishrock123** [comment]
Either @aks- or @thefourtheye might also be good for the entire non-native english / international-timezone thing. (India)

(Note: scheduling a meeting may become very difficult.)

**Comment by thefourtheye** [comment]
I am in. Thanks for the ping @Fishrock123

**Comment by sup** [comment]
@thefourtheye :+1:

**Comment by Fishrock123** [comment]
Also, possibly @jungminu for the International timezones / non-native english thing. :)

**Comment by JungMinu** [comment]
@Fishrock123 Thanks a lot

**Comment by nebrius** [comment]
@thefourtheye, @JungMinu, thanks for volunteering! added to the list.

**Comment by jasnell** [comment]
@Fishrock123 definitely has my vote of confidence to represent the TSC/CTC so that's awesome to see him volunteer. I'll participate in discussions as much as time allows and help out in other ways as much as is possible.

**Comment by Fishrock123** [comment]
Quite frankly, I'm not sure I need to be involved at the meeting level. Mikeal sounds like a better idea.

**Comment by jasnell** [comment]
That works too! I just want to make sure there's an open, active and visible communication channel between this WG and the TSC.

**Comment by mikeal** [comment]
@Fishrock123 I'm not a voting member of the TSC, or any other group under the foundation for that matter, as my role in the foundation requires that I maintain a level of neutrality. Because I'm employed by the board I can't effectively represent the TSC to this group or represent this group to the TSC the way a voting member can. I can show up and effectively describe the governance structure since I authored most of it and I can also provide input in to services the board or the Linux Foundation might be able to bring.

**Comment by jasnell** [comment]
@mikeal ... good point, appreciate the clarification.

**Comment by juliepagano** [comment]
Based on discussions happening elsewhere, we may also want to talk about putting together moderation policies/guidelines in the meeting. 

When are we hoping to get this moving forward. Some time soonish?

**Comment by nebrius** [comment]
+1 to adding moderation to the agenda.

Maybe we could try for next week sometime?

@JungMinu, @thefourtheye, what timezone are each of you in?

**Comment by sup** [comment]
i'd be up for next week sometime

**Comment by ashleygwilliams** [comment]
indeed @juliepagano. already researching ban policies. 

im good with early next week. how about tuesday?

**Comment by sup** [comment]
tuesday sounds fine to me, +1

**Comment by nebrius** [comment]
I can do Tuesday

**Comment by juliepagano** [comment]
Tuesday should work for me.

**Comment by thefourtheye** [comment]
I should be fine with any day mostly, as long as I get a day or two notice before. @nebrius I am in Indian Standard Timezone (GMT +5:30) http://www.timeanddate.com/weather/india/chennai

**Comment by nebrius** [comment]
Does anyone have a non-typical daily schedule (goes to sleep really late, or wakes up really early)?

If not, I'd like to suggest: 16:00 UTC

08:00 PST
11:00 EST
17:00 CET
21:30 IST

How does this sound?

**Comment by sup** [comment]
:+1:

**Comment by nebrius** [comment]
For reference, just in case I miscalculated any 24 hour times: http://www.timeanddate.com/worldclock/meetingdetails.html?year=2015&month=11&day=17&hour=16&min=0&sec=0&p1=224&p2=179&p3=48&p4=54

**Comment by juliepagano** [comment]
Sounds reasonable to me.

**Comment by thefourtheye** [comment]
:+1:

**Comment by nathan7** [comment]
:+1:

**Comment by mikeal** [comment]
I'm at the Linux Foundation onsite next week but move forward without me,
this meeting can't happen soon enough. I can make myself available for a
followup with whoever ends up leading the efforts that fall out of it so I
can advise on any governance or foundation level considerations with your
plan.

**Comment by zkat** [comment]
I'd like to participate. I'll be back in the Bay by Tuesday.

**Comment by nebrius** [comment]
@zkat added you to the list, and added the time to the original comment

**Comment by sup** [comment]
sorry, but something in my agenda has happened which leaved me unable to talk at the set date. i'll still join and communicate/vote (i guess) via text. @nebrius, can you move me to the "less active role" list?

**Comment by nebrius** [comment]
@sup sorry to hear that. Would you perhaps be interested in and able to type in the chat window, and have someone else who is less active act as a stand-in and read everything out in the channel?

**Comment by sup** [comment]
@nebrius doesn't hangouts have a chat window so everyone can see what i type?

**Comment by nebrius** [comment]
@sup technically it does, yes. In practice, I've noticed that it often gets overlooked, and it can be hard to have a real time conversation between a group of people talking and a group of people texting. I'm hoping that having someone play the role of bridge between the two should make it more effective. We don't want to miss your input :)

**Comment by sup** [comment]
@nebrius then i guess it'd make sense to have someone who 'monitors' the chat window

**Comment by nebrius** [comment]
A few thoughts on logistics for tomorrow to make sure the meeting goes well.

Given the interest of 4chan/8chan in this working group lately, I think we should make the invite link private to ensure they don't try and disrupt the meeting. Note that this will be an on-air hangout, so anyone who wants to can still listen live, and the video will still be posted online for everyone to watch who wants to. @sup, @thefourtheye, @JungMinu, can I get your email address? If you don't want to post it publicly here, you can DM me on twitter (@nebrius there too). If that's not a good way, let me know and we'll figure something else out.

I recommend we have three roles filled by people in the less active category (I'm willing to take on one of these roles):
- Moderator. Makes sure that the conversation is kept on-topic, and that we manage time properly. We could easily fill hours of conversation with everything we have to discuss, so keeping it to an hour will require discipline on the part of the moderator
- Note taker. Most important is recording any action items and resolutions
- Voice/Text bridge for people participating via the chat window so that we don't accidentally forget about them (the UI design of Hangouts makes this pretty easy)

Finally, I think we should try and all log in about 5-10 minutes early so we can make sure we get all the audio/video issues worked out before the meeting starts. This way we can have a little more time to talk.

**Comment by sup** [comment]
@nebrius my email's jona@jona.io, and +1 for the 10 minutes earlier strategy

**Comment by zkat** [comment]
a couple of us did the facilitator training: myself, Rich, and Forrest. I'd
volunteer but I also really want to participate.

On Tue, Nov 17, 2015, 01:22 jona <notifications@github.com> wrote:

> @nebrius <https://github.com/nebrius> my email's jona@jona.io, and +1 for
> the 10 minutes earlier strategy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodejs/inclusivity/issues/13#issuecomment-157317015>.
>
-- 
kat

**Comment by ashleygwilliams** [comment]
i'm happy to be moderator if we don't have one.

i'd like to add resolving the "new alternative charter" from @jasnell to the agenda #27

**Comment by ashleygwilliams** [comment]
actually, after talking with @zkat i think it makes a lot of sense for both of us not to facilitate since we need to actually participate. perhaps @othiym23 or @Trott ?

**Comment by nebrius** [comment]
+1 to @othiym23 or @Trott to facilitating, if either of you are ok with that

**Comment by Trott** [comment]
I have a conflict and will be missing most of the meeting, I'm sorry to say. (I didn't put myself down as an attendee in this issue, so it didn't seem worth mentioning until now, with the whole facilitator thing.)

**Comment by nebrius** [comment]
@thefourtheye, I invited you to a google hangout, did you get the invite?

**Comment by thefourtheye** [comment]
@nebrius Nope, not yet :'(

**Comment by nebrius** [comment]
@thefourtheye I directly emailed you a link, let me know if it works!

**Comment by nebrius** [comment]
Here's the public link for the hangout for anyone who would like to watch http://youtu.be/oBkMYONPYp8

**Comment by ashleygwilliams** [comment]
CONGRATS YA'LL. we did it. i even dare say i enjoyed it. and i was terrified. <3

**Comment by zkat** [comment]
👏

**Comment by sup** [comment]
same here

**Comment by sup** [comment]
now could we maybe rename this into `11/17/2015 Meeting` or something like that? would make sense

**Comment by zkat** [comment]
Renaming this to follow along with the pattern set up in node/LTS

**Comment by sup** [comment]
:+1:
