### ISSUE TITLE
De-gitter-ize

### ISSUE THREAD

**Issue by Trott** [nodejs/inclusivity#136]
We have IRC channels and Gitter rooms too. It seems like for most (all?) projects in nodejs, use of Gitter by heavily-involved-in-the-project folks and moderation of Gitter seem to be low.

We would probably be doing everyone a favor by either:
- removing Gitter links from README and other docs in favor of IRC links

OR:
- making sure we have people that are active in the Gitter rooms and that they have any necessary moderation tools

**Comment by tentakel** [comment]
are you referring to all node repos?

**Comment by Trott** [comment]
@tentakel asked:

> are you referring to all node repos?

All repos in the `nodejs` organization, yes.

**Comment by tentakel** [comment]
@Trott yeah, i agree. it'd be ideal if there was a service that provided badges that link to a tutorial on how to join an irc room (since irc is more active in this case).

**Comment by nathan7** [comment]
@tentakel We could probably link to Freenode's web chat quite easily

**Comment by TheAlphaNerd** [comment]
@nathan7 one step further ==> https://webchat.freenode.net/?channels=node-dev

**Comment by nathan7** [comment]
@thealphanerd yup, that was my intention, just a little too tired to figure out the URL schema :heart:

**Comment by TheAlphaNerd** [comment]
I've 100% spent more than 5 minutes in the past trying to remember it... guessed right quickly this time

**Comment by mcdonnelldean** [comment]
Are the Gitter channels still being used (albeit outside of heavily involved users). I spend a lot of time on Gitter and I'm happy to help feed users to IRC to make the transition easier.
