### ISSUE TITLE
Slack Inviter Site Not Found

### ISSUE THREAD

**Issue by bnb** [nodejs/inclusivity#145]
Looking for a Slack Inviter for a Node community, and I came across the one built for the Invlusivity WG. I wanted to see how it worked, so I came to this repo and went to the Inviter link, but it's throwing an Unable to Connect error in both Firefox Developer Edition and Safari.

Just thought I'd let you know.

**Comment by scottgonzalez** [comment]
Apparently the database got wiped, so the server crashed when it tried to access it. @nebrius any idea why that would have happened? I just logged into the server, reran the setup script to create the database tables again and then restarted the server.

@bnb Please try again and let us know if you're able to join using the inviter.

**Comment by nebrius** [comment]
@scottgonzalez _shrugs_, I have no idea why that would have happened. Let's keep an eye on it and see if it happens again.

**Comment by truedat101** [comment]
Is this the inviter site?  http://node-inclusivity.nebri.us

Definitely not accessible.

**Comment by TheAlphaNerd** [comment]
afaik the slack is no longer run. @nebrius should you shut that down and remove references to it?

**Comment by nebrius** [comment]
The slack is _technically_ running, as in I can log in to it, but no one has posted since August or so. The slack inviter hasn't been very stable unfortunately, and probably crashed again :-/

**Comment by TheAlphaNerd** [comment]
@nebrius is it perhaps time to shut down the slack if it isn't being actively used / moderated?

/cc @hackygolucky

**Comment by williamkapke** [comment]
or perhaps it will be used once again when the new Community Committee is up and running?

... I guess I'd rather see it renamed to something more general then I guess 🤔
