### ISSUE TITLE
Inclusivity WG at Node Interactive North America

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/inclusivity#151]
## Purpose
WG meeting at Node Interactive call for attendance and discussion

## Proposal
I'd love for those who will be at Node Interactive and would like to talk about the strategy moving forward to have time to do so. I'm going to be filing for time during [Collaboration Summit](https://github.com/nodejs/summit/issues/35) so that there is space allotted for those who are interested in participating in these conversations a private space to do so(you don't have to be a current member of the Inclusivity WG, but there will be guidelines/CoC to help with communicating kindly in this private space). The strategy laid out for the short term is very high level and needs implementation details laid out by the Inclusivity WG and larger community. This would be a great in-person session to get this started in.

## Focus
For those of you who missed it, the [TSC proposed an investigation into future responsibilities](https://github.com/nodejs/TSC/issues/133) and that task was taken on by @hackygolucky from the Node.js Foundation. The results of that investigation are going to be shared with Inclusivity and the TSC, November 27(the deadline for input from the Board of the Foundation).

If you'll be there, please comment below! It'd be awesome to see a combination of new and legacy faces at the table.

**Comment by Trott** [comment]
I'll be at Node Interactive in Austin so I should be able to go to this.

**Comment by nebrius** [comment]
I'll be there.

**Comment by Trott** [comment]
> The results of that investigation are going to be shared with Inclusivity and the TSC,

Would it be possible to share the results here, in the issue tracker? Or, if confidentiality is needed for the time being, perhaps via email to the people listed as WG members in the README?

**Comment by hackygolucky** [comment]
Ah yes! I should have been explicit in stating it will also be posted at
the same time to the Inclusivity WG.  It is most relevant here of all
places.

I'm also happy to seek guidance via email. Thanks @trott

**Comment by Trott** [comment]
Is there any reason to wait until the end of the month? Can the results, or a draft, be shared now-ish?

**Comment by hackygolucky** [comment]
I gave the Board until Nov. 27 to share any feedback before I published it
for the TSC. I guess that certainly does not negate granting access to the
doc for folks interested in the Inclusivity WG and then I can share with
the TSC at large after that date.

**Comment by nebrius** [comment]
FYI I updated https://github.com/nodejs/summit/issues/35 to include the Inclusivity session. For the time being, I listed myself and @hackygolucky as the leads for the session. Does this work for you @hackygolucky? I'm also fine taking either you or myself off as organizers.

**Comment by hackygolucky** [comment]
Thanks @nebrius! I was waiting to hear back for interest. Sounds great.

**Comment by nebrius** [comment]
I bet a number of people will be interested. This repo doesn't have many eyes on it anymore, so I wouldn't expect much activity in this thread.

**Comment by hackygolucky** [comment]
Just [signed us up](https://docs.google.com/spreadsheets/d/1gJoyiq0z6rjS7jEoHkRe6jte8Dd7ZBkwD3WjOh6djvQ/edit?ts=583e17e9#gid=0) for meeting in "Outside Griffin #1" on Dec. 2, 11am-12pm. Let me know if y'all really want to attend and that conflicts! If we end up hashing it out the afternoon prior at the first afternoon of the summit, that's fine by me, too.
