### ISSUE TITLE
Opt-in COC and review panel

### ISSUE THREAD

**Issue by hueniverse** [nodejs/inclusivity#2]
We recently decided to add a formal COC to the hapi.js project. Writing a COC isn't too hard as there are plenty of great examples or steal from. The problem is how to operate the COC once issues are brought up.

I am trying to avoid forming a COC committee for hapi.js which in turn will need to come up with rules and bylaws and membership... It's pretty much a full project all on its own.

I am hoping the node.js foundation can provide such a service. Basically, it will publish a COC and review process for reported violations that any project can chose to opt into and abide by. The review panel will receive reports and will decide what's the right response and will provide it to the project leads (at which point it is their job to carry out the decision).

Otherwise, we are likely to see projects adopting a whole bunch of different COCs and then no real process for acting on reported violations.

**Comment by 2manyprojects2littletime** [comment]
COC = code of conduct?

**Comment by mikeal** [comment]
> COC = code of conduct?

Correct.

**Comment by isaacs** [comment]
@2manyprojects2littletime yes.

**Comment by nebrius** [comment]
@hueniverse we're discussing it now in the diversity WG, so stay tuned!

**Comment by nebrius** [comment]
If you're curious, feel free to read over and comment on https://github.com/nodejs/hardware/pull/7. The hardware WG is a little older, and this further along in setting up contributing guidelines.

**Comment by dangerrust** [comment]
I feel that it's important to refer to a Code of Conduct by its full name, and not by the acronym "COC", which is, quite frankly, offensive, sexual, and problematic.

**Comment by scottgonzalez** [comment]
This is an interesting idea, though I wonder how many projects the foundation can effectively manage at once. I don't think the number could be very high if there's active monitoring, but just being available to handle incident reports can probably scale pretty well based on the current frequency of incidents.

**Comment by jden** [comment]
While I don't think it should be necessary for each project to develop their own COC as a "full project" as you say, there *is* value in actively discussing values and ground rules in a group and making a deliberate choice to adopt a given code of conduct, rather than just having it as a *pro forma* box to check off. In addition to providing a COC and review process for projects in the node community, it would be great to have an implementation guide with guidance on how to introduce and publicize the COC.

**Comment by scottgonzalez** [comment]
> there is value in actively discussing values and ground rules in a group and making a deliberate choice to adopt a given code of conduct, rather than just having it as a pro forma box to check off.

I completely agree. Any project opting in to this should have to go through some form of onboarding where the foundation representatives and project maintainers go through the terms of the CoC. The foundation must have confidence that the individual projects understand the policies, how to recognize problems, how to report incidents, etc.

It'd probably be a good idea to have regular check-ins with the projects as well. These probably don't need to happen very often though.

**Comment by nebrius** [comment]
I think this sounds like a great idea, I like the idea of this WG serving as a resource for setting up a CoC and providing advice to groups on how to implement one successfully. As @scottgonzalez said, this should scale pretty well.

**Comment by Trott** [comment]
I'm going to close this as the WG is inactive and superseded by the Community Committee. Will @-mention @nodejs/community-committee in case this is something they want to take on and move to their repository. Feel free to comment (or re-open if GitHub permits) if you feel closing this is inappropriate.
