### ISSUE TITLE
Node Inclusivity WG and facilitation core competency?

### ISSUE THREAD

**Issue by zkat** [nodejs/inclusivity#28]
**THIS IS NO LONGER A DISCUSSION THREAD** -- This is an agenda item for a WG meeting. Any further discussion will be heavily moderated. Please see #37 for details. Keep discussion here as clarifying the scope of the discussion to be had. No decision will be made here.

Since nodeconf adventure, we started having facilitators participate in both technical and community-related conversations, thanks to @groundwater. Since then, he trained three additional people (@zkat, @othiym23, and @Trott) who then helped facilitate in the Node Collaborator Summit. I definitely got the impression this was appreciated by the majority of participants.

I would like to propose that the WG, as one of its responsibilities, take on the task of both training new facilitators, and being a source for them that can be requested/borrowed by other WGs and the TSC when discussions come up that would benefit from the skill. The main reason I propose it in this WG is because all of us that went through that training stuff are in this WG right now, and a large part of facilitation _is_ to help make sure voices are heard and conversations are kept in line. It's also an additional deliverable that can be an ongoing effort for this WG.

**Comment by sup** [comment]
could you define 'facilitator' in this context?

**Comment by zkat** [comment]
Facilitation is a method of guiding community conversations in such a way that voices are heard all around, and specific things are better-defined, and finally determining concrete actions that a good number of participants are comfortable with. It's a bit more than just "keep it civil" and involves concrete techniques that you need to train people on.

**Comment by sup** [comment]
oh, i see. thanks

**Comment by juliepagano** [comment]
This sounds awesome to me. :)

**Comment by ashleygwilliams** [comment]
as i said in today's meeting (#13) i think this is a *fantastic* idea and a great way to begin to provide services to the greater community.

**Comment by beaugunderson** [comment]
huge +1; I'd like to learn this skill as well

**Comment by nebrius** [comment]
I would like to learn too, especially since I was sick during the last training and had to skip it

**Comment by TheAlphaNerd** [comment]
I would take part in this
