### ISSUE TITLE
Consider forking

### ISSUE THREAD

**Issue by mvirkkunen** [nodejs/inclusivity#29]
It seems that the concerns of this "working group" are not entirely in line with software development as a whole, i.e. quality of code and swift implementation of features.

If you absolutely must continue, I suggest forking the Node codebase to get your own cleaned-up version. Maybe call it "Node plus inclusivity". Then you can use all the time you want on censoring comments and commit messages and other things that affect the working of the software in no way. 

That way people who have a sense of humor and/or can understand words in context correctly can work on and use the upstream version without being hindered by your policies, and the few who are triggered by words such as "host" or "disabled" in comments can use your version.

Your working group could then implement its policies while doing merges from upstream, assuming you have time for that from your other duties. But merging in new features is secondary, right?

**Comment by TheAlphaNerd** [comment]
@mvirkkunen it seems you are being persuaded by internet hysteria and have not read through the various threads.

The point of this working group is to improve the ecosystem, period.

**Comment by mvirkkunen** [comment]
I guess we have a different opinion on what counts as an improvement to software.
