### ISSUE TITLE
Inclusivity WG Meeting - 2015-11-24 08:00 PST

### ISSUE THREAD

**Issue by zkat** [nodejs/inclusivity#37]
# Invited

* @nodejs/inclusivity
* @zkat (facilitator)
* @beaugunderson (Note-taker)
* @mikeal (Foundation)
* @Fishrock123 (TSC)
* @chrisdickinson (TSC)
* @ashleygwilliams (member)
* @juliepagano (member)
* @othiym23 (member)
* @thefourtheye (member)
* @nebrius (member)
* @sup (member)

Kat has volunteered to act as the facilitator for this session -- this means she won't have direct input but will help communication between participants happen smoothly. If you would like to be included, and you are a member of the WG, please comment below with the agenda items you'd particularly like to participate in if possible (or just don't mention any in particular).

Note to guests: **This is not a discussion thread**. Please refrain from addressing specific issues, and use the comments strictly to propose agenda items or request participation **if you are a WG member**.

## Participation

* [Hangout on Air for Participants](https://plus.google.com/hangouts/_/hoaevent/AP36tYdbMzknVdS0Bh06sqBBoxAgNmZBLhR6S3pgNrbfh1EklSRcpQ)
* [Broadcast link for observers](http://www.youtube.com/watch?v=8zodaTereaU)

# Agenda

The group is young, and we've seen a lot of points come up in the past week since activity started up again. This meeting is a good time to hash out communication and understandings about strategies and scopes for this working group. You'll note that there are no inclusivity-specific agenda items, and most of it is based around understanding where we are as a WG and where to go from here, structurally.

To propose additional agenda items (and be included in the meeting), please create an issue stating the item to be added and mention it in the comments here. Please avoid specific points about the agenda proposal, and simply state what the item is, and how it fits into the scope of the meeting, along with any questions you're hoping the agenda item can answer (again, within the reasonable scope of the meeting). We will update the threads with the results of our discussions. Please do not use agenda issue threads for open discussion.

## nodejs/inclusivity

* Scope of Inclusivity Working Group Charter and CoC - #38 
* Moderation and issue management in WG - #41
* Meeting structure and agenda process - #42
* Private/public balance - #40
* Membership vetting process - #39
* Facilitation as a core competency of WG - #28
* Proposal process for TSC implementing wider-ranging process changes - #43
* Moderation in wider Node community - #44

**Comment by jasnell** [comment]
I will be on vacation and will not be attending.

**Comment by zkat** [comment]
Sorry, @jasnell -- is there someone you feel can effectively represent the things you want to talk about, in relation to the agenda items above? Perhaps they can join, instead.

**Comment by jasnell** [comment]
If I have input I will participate via the github issue tracker as time
allows. If the goal is to have TSC representation, any of the other TSC
members would be more than qualified (likely more so than I).

**Comment by zkat** [comment]
Note that for the time being (most likely the next week or so), I'd like to reduce the noise on the issue tracker as much as possible -- that means my preference is to simply not have any substantive discussions outside of the meeting, until we're able to hash out better processes for having positive, productive discussions. I don't think we're ready to use github issues yet, but this is one of the main things we'd like to talk about during the (public) meeting next week. Not that the results will be set in stone, either.

**Comment by 950c** [comment]
Does the meeting take place on the 11th day of the 24th month of 2015?

**Comment by zkat** [comment]
Thanks for the heads up. Go figure that I'd mess up when trying to use a date format precisely because it would disambiguate the weird US date order :)

**Comment by nebrius** [comment]
I would like to participate, as I did some initial work on the membership vetting process.

Do we want to do a 1 hour meeting again? It may be nothing, but I am a bit concerned we won't have enough time to get to all of the agenda items. Maybe we could do a longer meeting? Or perhaps we could do two sessions in the same day/a day apart? (Just brainstorming here)

**Comment by zkat** [comment]
My suspicion here, when I made the agenda items, is that most of these are actually really uncontroversial. Most of the issues we're seeing with WG mechanics seem to be misunderstandings about the attitude and scope of this WG. I think the actual contents of what we want are mostly in alignment, and a short but facilitated discussion that we can document might be all we need to move forward.

**Comment by nebrius** [comment]
ok, that makes sense then

**Comment by thefourtheye** [comment]
I am in

**Comment by sup** [comment]
i'm in as well unless something comes up (which it shouldn't)

**Comment by zkat** [comment]
(the meeting is full at this point -- 10 people is the max for the hangout)

**Comment by zkat** [comment]
Thanks all for participating! I'll put up an issue for the next WG meeting when we figure out when and how to have it next. Please remember to update issues relevant to you/assigned to you and such. See you next time~

**Comment by thefourtheye** [comment]
Sorry people. Chennai is full of water. Couldn't get much time with computer :(

**Comment by Trott** [comment]
Yikes! http://www.weather.com/news/weather/news/dozens-dead-chennai-india-floods

Stay safe, @thefourtheye!

**Comment by ashleygwilliams** [comment]
<3 don't worry about it @thefourtheye -- and yes, what @Trott said, stay safe!

**Comment by nebrius** [comment]
oh no, be careful @thefourtheye!
