### ISSUE TITLE
Membership vetting process

### ISSUE THREAD

**Issue by zkat** [nodejs/inclusivity#39]
We should at least start talking about strategies for vetting new members into this WG. I think we may need to hash out some specifics in re goals before we can fully figure this out, as well as have some understanding of existing Foundation processes for this.

Also noting in particular the private and public parts of this WG and potential distinctions to be made in the process (should there be two types of membership, etc)

**Comment by zkat** [comment]
Ahh, it was in a PR. Crosslinking to #32, since @nebrius had an initial version of this (though we should still limit discussion to the meeting)

**Comment by ashleygwilliams** [comment]
closing as duplicate https://github.com/nodejs/inclusivity/issues/11
