### ISSUE TITLE
Moderation and Issue Management within WG

### ISSUE THREAD

**Issue by zkat** [nodejs/inclusivity#41]
We've been seeing a lot of issues with moderation come up recently, and it's worth discussing some specifics, and strategies for managing some of them. A list off the top of my head that I would at least like to bring up:

* Managing brigades and hostile actors
* Preventing multiple directed responses to individuals? ("dogpiling")
* Other strategies for reducing overall temperature of discussions
* Scope of Issue and PR usage in nodejs/inclusivity -- how much discussion should happen there vs WG meetings?

**Comment by Fishrock123** [comment]
Related to https://github.com/nodejs/TSC/pull/16

**Comment by nebrius** [comment]
I'm going to do some research into banning at the repo, not org, level and I'll report my findings here.

**Comment by nebrius** [comment]
#57 has been filed to help address some of these issues

**Comment by nebrius** [comment]
So here's the results of the banning research: it's currently not possible to block at the repository level, only at the org level. Further, only org owners can block. They noted the request for maintainers to be able to block at the repository level for future conversations.

**Comment by nebrius** [comment]
Results of the investigation: there is not currently a way to ban at the repo level, and it's not possible for someone other than an owner to ban people at the org level. _sad face_

**Comment by sup** [comment]
now that nodejs/TSC#16 has landed, the question if we should adopt the moderation policy or employ our own one is coming up. thoughts?

**Comment by zkat** [comment]
These things were discussed in [the 2015-11-14 WG meeting](https://github.com/nodejs/inclusivity/blob/master/meetings/2015-11-24.md#moderation-and-issue-management-in-wg---41) but I want to make sure we have issues set up for the concrete things we're planning on doing for each item before this is marked as closed.

**Comment by jasnell** [comment]
@nebrius ... the team at GitHub is very open to receiving feature requests. It might be worthwhile sending in a feature request asking that users with admin rights to an org repository be given the ability to block at the individual repository level. You can use the form [here](https://github.com/contact) to submit feature requests... just be sure to include some contextual detail as to why the feature would be helpful and how you envision it working.

**Comment by nebrius** [comment]
thanks @jasnell! Feature request submitted :)

**Comment by nebrius** [comment]
I filed #132 to address moderation on a broader scale. Do we think that program address the issues listed here as well? Or should we leave this issue open?

**Comment by nebrius** [comment]
Closing in favor of #132, feel free to reopen if need be
