### ISSUE TITLE
Meeting structure and agenda process

### ISSUE THREAD

**Issue by zkat** [nodejs/inclusivity#42]
I've done my best to emulate what I've seen in the LTS WG as far as meeting and agenda processes go. We can use this particular item to discuss it further, propose improvements, or highlight potential issues. This is a good place to discuss how often we'll be meeting, hours, etc.

Another issue I'd like to bring up with this agenda item, which is related to #40, is whether this WG should have a "private" component to its meetings.

**Comment by zkat** [comment]
This was pretty much uncontroversial in the [2015-11-24 WG meeting](https://github.com/nodejs/inclusivity/blob/master/meetings/2015-11-24.md#moderation-and-issue-management-in-wg---41) and we mostly need to make sure stuff from there gets written down in order to close this.

**Comment by jasnell** [comment]
@zkat ... if you haven't discovered it already, @rvagg has a repository with a set of CLI tools that are quite useful. One of which is the `node-meeting-agenda` tool that goes out and extracts a list of issues tagged with a specific label for the purpose of constructing meeting agendas.
