### ISSUE TITLE
Realtime scribe during meetings

### ISSUE THREAD

**Issue by scottgonzalez** [nodejs/inclusivity#54]
The first WG meeting was a video call and there was discussion of how future meetings would be held. Video (and voice) calls are difficult for some people to participate in (people who are non-fluent speakers, have poor hearing or deafness, speak with thick accents, have speech impediments, are mute, etc.). Even for for fluent speakers, if they're stuck in a location with a poor network connection or lots of background noise, participating in a voice or video call is difficult.

It's easier to keep track of, and participate in, the conversation if the meeting is written out in text. However, the benefits of actually talking are fairly high for those who do speak English fluently. The W3C WGs that I've participated in do both: They have a voice call but also have a scribe who writes notes in real time in IRC. Perhaps this would be something we can do for the inclusivity meetings as well.

**Comment by jden** [comment]
This would be wonderful- it's easier to read transcripts quickly and *~~~search~~~* is wonderful.

**Comment by beaugunderson** [comment]
I've volunteered to take notes for the next meeting; I'm a fast typer but not a transcriptionist. Happy to make them available in realtime as well (in etherpad or Google doc or something like that).

**Comment by zkat** [comment]
This sounds like a great idea and I'd like to include it in the next WG meeting -- would you be willing to represent this point and help us figure out something that works for the group?

**Comment by zkat** [comment]
nm I already suggested that in #20 lolol sorry

**Comment by scottgonzalez** [comment]
No problem. I briefly talked to @ashleygwilliams about joining the other day, but the process for joining isn't quite clear yet. There's #39 and #32, but nothing to actually act on right now.
