### ISSUE TITLE
Task assignment after WG meetings

### ISSUE THREAD

**Issue by zkat** [nodejs/inclusivity#58]
I propose resolve `agenda-item` issues whenever they get discussed in our meetings, and preferably find volunteers to do whatever task (or at least take care of taking the next step and handing it over to the next person) so we don't leave the stuff we talked about hanging.

**Comment by juliepagano** [comment]
Closing this since it was discussed in the meeting. People agree that we should handle things this way, but that the work should not fall on any one individual (currently, @zkat has been doing a lot of this). Created #64 to identify a process to share the load across the team.
