### ISSUE TITLE
Inclusivity WG Meeting - 2015-12-18 10:00 PST

### ISSUE THREAD

**Issue by zkat** [nodejs/inclusivity#59]
# Invited

* @nodejs/inclusivity
* @Trott  (facilitator)
* @beaugunderson (Note-taker)
* @mikeal (Foundation)
* @Fishrock123 (TSC)
* @chrisdickinson (TSC)
* @ashleygwilliams (member)
* @juliepagano (member)
* @othiym23 (member)
* @thefourtheye (member)
* @nebrius (member)
* @sup (member)
* @zkat (member)

Note to guests: **This is not a discussion thread**. Please refrain from addressing specific issues, and use the comments strictly to **propose agenda items or request participation if you are a WG member**.

## Participation

* [Hangout on Air for Participants](https://plus.google.com/events/cvor13am1vm65ljth55meud5ma0)
* [Broadcast link for observers](http://www.youtube.com/watch?v=E6eNGLWwmzk)

# Agenda

This meeting is a continuation of the [previous meeting on the WG's structure](https://github.com/nodejs/inclusivity/blob/master/meetings/2015-11-24.md), and takes off from the same agenda items as the last meeting, minus the ones that were discussed.

If you're a WG member (or some other member of the Node Foundation), feel free to propose or request reordering of the agenda. This is the last meeting for this year so it might be nice to make sure we've talked about the basic things we want to talk about before end of year!

We will update the threads with the results of our discussions. Please do not use agenda issue threads for open discussion.

## nodejs/inclusivity

* Task assignment after WG meetings - #58
* Private/public balance - #40
* Membership vetting process - #39
* Facilitation as a core competency of WG - #28
* Proposal process for TSC implementing wider-ranging process changes - #43
* Moderation in wider Node community - #44

**Comment by Fishrock123** [comment]
Sounds good. Please send a Gcal invite so that we remember haha. :)

**Comment by juliepagano** [comment]
I'd propose taking the facilitation one off for this meeting. It seems like people are generally happy with facilitation and a bunch of folks want to learn, so it's largely an issue of figuring out how to train more people and get a nice rotation of facilitators when we've done that. With the holidays coming up and distracting people, we'll probably be better off trying to make movement there in the new year.

**Comment by thefourtheye** [comment]
Still recovering from the Chennai flood. I am afraid I'll be missing this meeting. Sorry :(

**Comment by Trott** [comment]
I'm sick and am having difficulty speaking. I'm not sure how effective I'm going to be at this meeting.

**Comment by Trott** [comment]
Video of the meeting: https://www.youtube.com/watch?v=KdV69lFQrnU
