### ISSUE TITLE
inclusivity checklist/guide for conference organizers

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/inclusivity#61]
this is a guide/checklist that we can make available to the Node Foundation/Linux Foundation, as well as other local Node groups, to help them make inclusive spaces for their events with the hopes of improving diversity.

it should include:
- groups to reach out to
- considerations re: food/family (allergies, childcare, etc)
- how to present a code of conduct
- how to enforce a code of conduct

more suggestions welcome (this is def an incomplete list)! please share links here and we'll make a PR where we collect links and tips into a single doc.

**Comment by TheAlphaNerd** [comment]
Could be interesting to include a list of charities and non-profits to donate proceeds to

**Comment by ashleygwilliams** [comment]
ooh that's a great call @TheAlphaNerd -- so much so that i made it it's own issue! https://github.com/nodejs/inclusivity/issues/63

**Comment by beaugunderson** [comment]
@Charlotteis: assigned us both since you mentioned having thoughts about this :)

**Comment by beaugunderson** [comment]
@scottgonzalez mentioned this resource as well: https://github.com/cascadiajs/how-to-conf
