### ISSUE TITLE
pre-conference education event

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/inclusivity#62]
i've been speaking with @mikeal about this. this would be a 1-2 day event that happens prior to a conference that helps beginners get up and running with node.

i'll be making a PR with more details forthcoming.

**Comment by TheAlphaNerd** [comment]
I was talking with @jasnell today that it could be interesting to make a nodeschool workshopper that helps you get node installed. Still not 100% how the first couple steps could be installing itself, but perhaps a more visually driven electron app could help

**Comment by sup** [comment]
@TheAlphaNerd can we make that an actual issue on a nodeschool repo or on here? i'd be super interested in helping out with that

**Comment by TheAlphaNerd** [comment]
that's a great idea. do you want to take the lead on that?

**Comment by sup** [comment]
sure! is there a good repo i can start this on?

**Comment by TheAlphaNerd** [comment]
I'd say perhaps the node evangelism tracker --> https://github.com/nodejs/evangelism/issues

This seems like it could be a good top level project for that org

**Comment by mikeal** [comment]
A few questions:

1. Should we run this before or after the event? If we run it after we have the benefit of promoting it *at* the event.
2. At one point we talked about an "Install Fest" which I think is genius. We consistently underestimate the work required to get a dev environment setup the first time. Also, whenever I've done "beginner workshops" a good number of people show up expecting something far more advanced but "Install Fest" sets the expectations pretty clearly.

Also, in the new year the foundation will be running many events of varying length. Some just an evening meetup length, some one day, and some larger events like Node.js Interactive. So the more flexible we make this program the easier it will be to slot in to all of these events.

**Comment by sup** [comment]
https://github.com/nodejs/evangelism/issues/200 is up, feel free to do an idea dump there

**Comment by mikeal** [comment]
Also, I love NodeSchool but I don't think it's a good fit for first install and dev environment setup. A more traditional workshop works better because people have *huge* variances in their existing environments and preferred tools. Node.js is now available in pretty much every IDE and editor, it's just a matter of configuration, and I think it's best to get people setup in whatever they are more familiar with rather than pushing them toward Atom or something more standardized.

**Comment by sup** [comment]
if i may plug something here, i've been having an idea for a more pedagogic approach on node tutorials over at here -> https://github.com/nodegood/nodegood

maybe we can make something out of this?

**Comment by TheAlphaNerd** [comment]
@mikeal I was imagining that electron would be used to embed a copy of node and a terminal to make it easier to get people up and running and transition them to their own environemnt

**Comment by mikeal** [comment]
@TheAlphaNerd sure, but think about how many variance there are, you have every operating system, multiplied by several install choices, each with their own possible permission issues. Then once it's installed you have a myriad of IDEs and Editors that might need to be configured. The best approach tends to be just sitting down as a semi-expert on Node.js and working with them on what they know about their setup to get it working.

**Comment by Charlotteis** [comment]
Confirmed with ag_dubs that Node Together is considered a pre-conference kind of event.
