### ISSUE TITLE
list of groups/charities/non-profits for outreach

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/inclusivity#63]
as per @TheAlphaNerd's comment on #61 i think this should be a separate document that lists groups/charities/non-profits we should reach out too. i think we should look to both node/js specific, as well as general, groups.

**Comment by TheAlphaNerd** [comment]
WaffleJS has donated to [girls who code](http://girlswhocode.com/) which has done an amazing job of making individuals feel like the event is a safe space (having talked to various people from under represented groups).

It might be night to get some testimonials from both participants and orgs about how important this can be

**Comment by carlosrymer** [comment]
There are various organizations in NYC associated with CS4All (Computer Science for All). Here are a few that are working with the city's Department of Education:

- [C/I (Code Interactive)](http://www.weare.ci/)
- [Academy for Software Engineering](http://www.afsenyc.org/)
- [Code.org](https://code.org/)
- [ScriptEd](https://scripted.org/)

It might even be of interest to partner with the city's DOE as an outreach strategy. More on CS4All [here](http://www.csnyc.org/).
