### ISSUE TITLE
Process for sharing administrative tasks around meetings and issue creation.

### ISSUE THREAD

**Issue by juliepagano** [nodejs/inclusivity#64]
This comes from discussion of #58 and [the 2015-12-18 meeting](https://github.com/nodejs/inclusivity/blob/master/meetings/2015-12-18.md). This administrative work is important for meeting preparation and follow-up. The team should share this work, so that nobody is getting burned out on it. The purpose of this task is to find a list of people willing to share this task and a good rotation process to make sure it's being shared.

**Comment by juliepagano** [comment]
It seems like we have several roles that go into our regular meetings. Some of these (facilitator, note taker) require some specialized skills. The rest are pretty generic things that most people can probably do given instructions (e.g. how to set up a hangout on air).

* **Scheduler** - Schedules a time for the meeting, sends an invite, and sets up the hangout.
* **Agenda preparer** - Prepares a meeting agenda and creates an issue on github prior to the meeting.
* **Facilitator** - Facilitates the meeting to keep things on track. Ideally has some facilitation training/skills. 
* **Note taker** - Takes notes during the meeting. Needs the ability to type quickly. Will flag action items in the notes and upload them to github shortly after the meeting. It is difficult to take notes and participate at the same time.
* **Action item preparer** - Reviews the notes from the meeting and creates issues on github for action items.

**Comment by juliepagano** [comment]
To start, it would be helpful to understand which people from the WG have the more specialized roles: facilitator, note taker. Could folks who have those skills and are willing to get in a rotation for them comment on here.

**Comment by beaugunderson** [comment]
note taker reporting for duty :sparkles:

**Comment by nebrius** [comment]
I can moderate in a pinch. I'm not formally trained in it (yet) and so I'm not particularly good at it, but have done it a few times.
