### ISSUE TITLE
Create early draft proposal for moderation in the wider Node community to facilitate discussion for a future meeting.

### ISSUE THREAD

**Issue by juliepagano** [nodejs/inclusivity#66]
This comes from #44 and discussion in the [2015-12-18 meeting](https://github.com/nodejs/inclusivity/blob/master/meetings/2015-12-18.md). A rough initial proposal will improve our ability to discuss this in a future meeting.

The purpose of this issue is to track assignment of this task following the meeting. A pull request will be created with a rough proposal when it is ready for discussion.

**Comment by nebrius** [comment]
I think that #132 includes this issue in it, so I'm going to close this issue. Feel free to reopen if you think we should.
