### ISSUE TITLE
Create early draft proposal for proposal process for TSC implementing wider-ranging process changes

### ISSUE THREAD

**Issue by juliepagano** [nodejs/inclusivity#67]
This comes from #43 and discussion in the [2015-12-18 meeting](https://github.com/nodejs/inclusivity/blob/master/meetings/2015-12-18.md). A rough initial proposal will improve our ability to discuss this in a future meeting.

The purpose of this issue is to track assignment of this task following the meeting. A pull request will be created with a rough proposal when it is ready for discussion.

**Comment by Trott** [comment]
https://github.com/nodejs/inclusivity/pull/68
