### ISSUE TITLE
get ratified by the TSC

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/inclusivity#69]
~~PR here: https://github.com/nodejs/node/pull/4355~~
PR here: https://github.com/nodejs/TSC/pull/29

**Comment by ashleygwilliams** [comment]
currently blocked by https://github.com/nodejs/TSC/pull/24

**Comment by sup** [comment]
which, in return, is blocked by nodejs/TSC#26 :P

**Comment by jasnell** [comment]
I don't consider https://github.com/nodejs/TSC/pull/26 to be a blocker.

**Comment by sup** [comment]
@jasnell isn't it a 'part' of nodejs/TSC#24?

**Comment by jasnell** [comment]
related to but it can be done in parallel

**Comment by sup** [comment]
ah, thanks for clearing that up

**Comment by ashleygwilliams** [comment]
unblocked! @jasnell landed my patch to add a working groups doc to the TSC repo in https://github.com/nodejs/TSC/commit/5eb8ab071b1a6a9eeb3342e958e4be6912c140b0

**Comment by ashleygwilliams** [comment]
officially waiting on https://github.com/nodejs/TSC/pull/29 now

**Comment by ashleygwilliams** [comment]
https://github.com/nodejs/TSC/pull/29#issuecomment-171771185, for posterity

**Comment by nebrius** [comment]
_happy dance_ 🎉
