### ISSUE TITLE
Inclusivity WG Meeting - 2016-01-08 10:00 PST

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/inclusivity#72]
https://plus.google.com/u/0/events/ccu921t1dl9ibne4v41ho0dai0o

## Roles
- Agenda: @ashleygwilliams
- Meeting Notes: @beaugunderson

## Agenda

-  <h3>Introductions</h3>
-  <h3>Working Group Operations</h3>
   - Add Code of Conduct Finalized https://github.com/nodejs/inclusivity/pull/22 (@ashleygwilliams)
      - Update on `inclusivity@` https://github.com/nodejs/email/pull/13, https://github.com/nodejs/TSC/issues/27 (@beaugunderson)
   - Update on Ratification https://github.com/nodejs/inclusivity/issues/69 (@ashleygwilliams)
      - Adding WG doc https://github.com/nodejs/TSC/pull/24 (@ashleygwilliams)
      - WG Boostrap https://github.com/nodejs/TSC/pull/26 (@jasnell)
   - Admissions 
      - Form? https://github.com/nodejs/inclusivity/pull/32, https://github.com/nodejs/inclusivity/pull/70 (@nebrius, @sup)
- <h3>Activities</h3>
   - Summary of work for Microsoft (@zkat)
- <h3>Open PRs</h3>
  - Issue Structure for Contributing Guide https://github.com/nodejs/inclusivity/pull/71 (@nebrius)
  - Proposal for upstreaming policies to TSC https://github.com/nodejs/inclusivity/pull/68 (@Trott)
- <h3>Deliverables</h3>
  - Schedule Next Meeting
  - What do we want to accomplish in the next two weeks?

**Comment by Trott** [comment]
I just closed #68 so you can remove that from the agenda if you wish. Or I can just give a two-sentence explanation that will amount to:  The content is now in the TSC repo and we can refer to it there.

**Comment by ashleygwilliams** [comment]
if you wouldn't mind, @Trott, i think a lil summary of what happened would be great :)

**Comment by nebrius** [comment]
Did you want to add #70 to open PRs? Does that need any discussion?

Also, a reminder that I won't be able to attend tomorrow, although please do still discuss the things assigned to me! :)

**Comment by beaugunderson** [comment]
Just noting that I'll be there to take notes again tomorrow. :sparkles:

**Comment by sup** [comment]
can't make it today, sorry!

**Comment by ashleygwilliams** [comment]
closed #73
