### ISSUE TITLE
TSC request for a nomination to the TSC.

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/inclusivity#78]
In [today's TSC meeting (2016-01-14)](https://github.com/nodejs/TSC/issues/31) the composition of the TSC was discussed somewhat. Along with that and the ratification of this working group, we'd like the Inclusivity WG to nominate someone (i.e. from this WG) who we could bring onto the TSC as a member.

[Quote from the notes:](https://docs.google.com/document/d/1jYeIgo3rEUyV0haqFQ4pEvo2lDVitJMWNeIXLRrssuM)
> * No objections, Inclusivity WG was ratified as a top-level WG, group agreed to reach out and ask them to nominate someone to the TSC (it was noted that we don’t have a formal requirement to add WG members to the TSC, just top-level _projects_.)

If you have questions about that responsibility, more info can be found at https://github.com/nodejs/TSC#tsc-members, and I’d gladly answer any others.

**Comment by Fishrock123** [comment]
(From the last inclusivity WG meeting, they are waiting until the board elections since two inclusivity members are running for the community board positions.)

**Comment by sup** [comment]
now that that's done, let's update the status on this, shall we?

**Comment by jasnell** [comment]
As a whole the WG should pick a representative. The decision process should likely follow the WG's typical process for consensus. If a decision can't be reach through discussion, put it to a vote :-) Beyond that, whatever process the WG wants to follow is up to the WG.

**Comment by hg** [comment]
the inclusivity working group hereby officially nominates @nebrius for the TSC position. sorry for the delay in this, it took us some time to coordinate a meeting in which we could discuss this.

**Comment by TheAlphaNerd** [comment]
🎉🎉 congrats @nebrius

**Comment by jasnell** [comment]
woot! awesome, I'll make sure @nebrius is included in the invite for the next TSC call if @rvagg doesn't beat me to it.

**Comment by nebrius** [comment]
thanks @hg, @TheAlphaNerd, and @jasnell! I'm looking forward to it!

**Comment by Charlotteis** [comment]
Congrats @nebrius.
Think this issue can be closed now? 💃

**Comment by 59** [comment]
absolutely, thanks for bringing that up @Charlotteis
