### ISSUE TITLE
Inclusivity WG Meeting - 2016-01-21 10:00 PST

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/inclusivity#80]
Participant Link: https://plus.google.com/hangouts/_/hoaevent/AP36tYcyJuPIWopnU4fgfXEVyeYShXfstw1CUkUOf5LdUiFHClDUuA?hl=en&authuser=0
Observer Link: https://www.youtube.com/watch?v=PONibium-Gk

## Roles
- Agenda: @ashleygwilliams
- Meeting Notes: @beaugunderson

## Agenda

-  <h3>Introductions</h3>
-  <h3>Working Group Operations</h3>
   - Contributing Overview: Policies? Programs? https://github.com/nodejs/inclusivity/pull/88 (@ashleygwilliams) 
   - Policy Issue Structure https://github.com/nodejs/inclusivity/pull/71 (@nebrius)
   - Admissions 
      - Form? https://github.com/nodejs/inclusivity/pull/32, https://github.com/nodejs/inclusivity/pull/70 (@nebrius, @sup)
     - Role Definitions https://github.com/nodejs/inclusivity/issues/65 (@juliepagano, @beaugunderson) 
        - Public/Private spaces
           - Cleaning up the Slack https://github.com/nodejs/inclusivity/issues/81 (@sup)
   - Moderation for Greater Node Community https://github.com/nodejs/inclusivity/issues/79 (@ashleygwilliams)
   - TSC Nomination Request https://github.com/nodejs/inclusivity/issues/78 (@fishrock123)
- <h3>Activities</h3>
   - ChakraCore was open sourced! Awesome job, ya'll! https://github.com/Microsoft/ChakraCore
- <h3>Open PRs</h3>
  - n/a
- <h3>Deliverables</h3>
  - Scheduling
     - Next Meeting (2 weeks)
        - Rotating Meeting Times https://github.com/nodejs/inclusivity/issues/74 (@trott)
     - Membership Applications (next week)
  - What do we want to accomplish in the next two weeks?
      - POLICY: membership roles https://github.com/nodejs/inclusivity/issues/65
      - POLICY: upstream "gender-identity" CoC change https://github.com/nodejs/inclusivity/issues/82
      - PROGRAM: getting started with contributing to Node document https://github.com/nodejs/inclusivity/issues/86
      - DOC: history document https://github.com/nodejs/inclusivity/issues/85

**Comment by Charlotteis** [comment]
Is it possible to sit in and just ~listen~? I'm not a member of the WG so I realise my attendance will only be possible if there is space. Being on a Thursday, I could stay later at work and attend :)

**Comment by beaugunderson** [comment]
@Charlotteis there will be a public Google Hangouts link for for watching the meeting happen in realtime; it will be available before the meeting starts (once we create the meeting event, which is still an ad hoc process at this point); you are more than welcome to watch using that :)

**Comment by sup** [comment]
the meeting's at 10 AM, yes? if so, i'll likely be joining ~15 mins in

**Comment by Fishrock123** [comment]
@sup Yeah, 10AM Pacific Time.

**Comment by nebrius** [comment]
Here's the direct hangouts link if the event page is giving anyone issues: https://plus.google.com/hangouts/_/hoaevent/AP36tYcyJuPIWopnU4fgfXEVyeYShXfstw1CUkUOf5LdUiFHClDUuA?hl=en&authuser=0

Also, I goofed a bit and set the time for PM, not AM. It's fixed now.

**Comment by Charlotteis** [comment]
I wanted to join direct, but I am in currently dishevelled and sick in a duvet. Really excited to watch along live though!

**Comment by bradley-holt** [comment]
Looking forward to observing the meeting!

**Comment by Fishrock123** [comment]
Observant link, live soon: https://www.youtube.com/watch?v=PONibium-Gk

**Comment by nebrius** [comment]
Closed #94
