### ISSUE TITLE
add responsibility of maintainers section a la chakracore

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/inclusivity#83]
add this to our CoC cuz its rad from [Microsoft/ChakraCore]:

> Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful.

> By adopting this Code of Conduct, project maintainers commit themselves to fairly and consistently applying these principles to every aspect of managing this project. Project maintainers who do not follow or enforce the Code of Conduct may be permanently removed from the project team.

[Microsoft/ChakraCore]: https://github.com/Microsoft/ChakraCore/blob/master/CODE_OF_CONDUCT.md

**Comment by Charlotteis** [comment]
Totally agree. I really loved reading this.

**Comment by ashleygwilliams** [comment]
wanna make a PR @charlotteis? would happily merge :smile:

**Comment by Charlotteis** [comment]
Do we want to link back to Chakra in some form as a mention?

**Comment by ashleygwilliams** [comment]
sure! always nice to give attribution. a bit of history: they asked us to review their CoC before open sourcing, so its via us by way of them kinda lol. iirc this was their emphasis tho? give em attribution cuz they are awesome :)

**Comment by Charlotteis** [comment]
Also where in the CoC? I was thinking under Scope and then a mention of thanks to Chakra.

**Comment by Charlotteis** [comment]
> they asked us to review their CoC before open sourcing, so its via us by way of them kinda lol.

:sparkles: communities working together :sparkles:

**Comment by ashleygwilliams** [comment]
i leave that up to you! your idea seems great.

**Comment by beaugunderson** [comment]
Also registering my support for this! :sparkles:
