### ISSUE TITLE
Create a history document

### ISSUE THREAD

**Issue by nebrius** [nodejs/inclusivity#85]
## Purpose

We should create a short document that chronicles the history of this working group and how it came to exist. It's a rather interesting story, and members of the WG who weren't there from the beginning have found it informative.

## Proposal

This document should contain a brief history that especially focuses on the initial creation at NodeConf Adventure 2015, and it's resurrection in October of 2015.

## Focus

Discussion of the points of history that occured is encouraged, but criticism/praise/analysis of those events should be considered off topic. The purpose of this document is to give a factual account of how this group came to be, not a critical analysis of that process.

**Comment by ashleygwilliams** [comment]
a nit, but i'd like to see this in a `doc` directory as i don't think it should be a top-level file

**Comment by nebrius** [comment]
good idea, will do!

**Comment by Charlotteis** [comment]
Yes please! I've now read through every closed/open issue (still got pull requests to read!) on this repo to get the backstory but I'm missing a lot.

I think:

-> everyone met up at a cool conf and got talking about making a WG
-> life got in the way, but then people started it back up again
-> originally named diversity but changed to inclusivity
-> lots and lots of discussion about scope
-> chartered!!!
-> the future :rocket: 

What I'd also propose is to make it a living document, putting in any great milestones in the WG.

e.g.
-> all the history mentioned above
-> jan: chartered!
-> mar: [name] joined the group
-> apr: [name] joined the group
-> jun: WG wins a prize (an example)

**Comment by sup** [comment]
@Charlotteis you're basically right, that's the history of this WG in 6 bullet points :P i also really like the milestone idea, but we need to avoid looking like we're showing off

**Comment by Charlotteis** [comment]
> you're basically right, that's the history of this WG in 6 bullet points

:dancer: 

> but we need to avoid looking like we're showing off

absolutely. With the right use of language, this could be great. Winning a prize was probably a poor example, but I couldn't think of anything better at the time.

**Comment by nebrius** [comment]
> What I'd also propose is to make it a living document, putting in any great milestones of the WG.

Great idea! I especially like the idea of adding when people were added to the group. We can probably back-date everyone who's already a member by seeing when they joined the slack (if we can see that of course).

**Comment by nebrius** [comment]
Pull request open at https://github.com/nodejs/inclusivity/pull/99

**Comment by williamkapke** [comment]
Hm.. It seems #99 finalized this topic?

Since this is still open, I'll use it to point out that the [README.md](https://github.com/nodejs/inclusivity#initial-membership) has an "Initial Membership" section and [history.md](https://github.com/nodejs/inclusivity/blob/master/docs/history.md#members) has a "Members" section.

That seems backwards to me.

**Comment by nebrius** [comment]
oh yes, #99 did finalize this topic. Are you suggesting we rename "Initial Membership" to just "Membership"? There's nothing initial about it, as it turns out 😅

**Comment by mikeal** [comment]
@nebrius good point. As more responsibilities get delegated to this group I would expect people to pop off and on more often based on their availability.

**Comment by nebrius** [comment]
The wording of "members" was cleaned up with #119, so I'm going to go ahead and close this issue.
